PREFIX="lamp"
GATEWAY="192.168.0.1"
NETMASK="255.255.255.0"
SERVERS=[
  {
    :HOSTNAME => PREFIX + "-001",
    :IP => "192.168.0.221",
    :CPU => "6",
    :RAM => "2048"
  }
]

Vagrant.configure(2) do |config|

  SERVERS.each do |machine|

    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.define machine[:HOSTNAME] do |node|

        node.vm.box = "ubuntu/jammy64"
        node.vm.hostname = machine[:HOSTNAME]
        node.vm.network "public_network", bridge: "wlp3s0",
          ip: machine[:IP],
          netmask: NETMASK,
          gateway: GATEWAY

        node.vm.provider "virtualbox" do |vb|
            vb.memory = machine[:RAM]
            vb.cpus = machine[:CPU]
            vb.name = machine[:HOSTNAME]
        end # END of provider

        node.vm.provision "shell", inline: <<-SHELL
          sudo ip route del default via 10.0.2.2
          # SSH Settings
          sudo sed -i "/#PubkeyAuthentication.*/a \PubkeyAcceptedKeyTypes=+ssh-rsa" /etc/ssh/sshd_config
          sudo systemctl restart sshd
          sudo apt-get update
          # MYSQL
          sudo apt-get install mysql-server -y
          sudo systemctl start mysql; sudo systemctl enable mysql
          # Apache
          sudo apt-get install apache2 apache2-utils -y
          sudo systemctl start apache2; sudo systemctl enable apache2
          # PHP 8.1
          sudo apt-get install php8.1 php8.1-fpm libapache2-mod-php8.1 libapache2-mod-fcgid \
          php8.1-mysqlnd php8.1-cli php8.1-common php8.1-opcache php8.1-mbstring php8.1-gd php8.1-curl -y
          sudo systemctl start php8.1-fpm; sudo systemctl enable php8.1-fpm
          sudo systemctl restart apache2
          # PHP FPM settings
          sudo a2enmod proxy_fcgi setenvif; sudo a2enconf php8.1-fpm
          sudo systemctl restart apache2
          # Content
          sudo rm -f /var/www/html/*
          # sudo echo "<h1>Test page</h1>" > /var/www/html/index.html
          # sudo echo "<?php phpinfo(); ?>" > /var/www/html/info.php
          # sudo chown -R www-data: /var/www/html
        SHELL

    end # END of define

  end # END of SERVERS

end
