PREFIX="node"
GATEWAY="192.168.0.1"
NETMASK="255.255.255.0"
SERVERS=[
  {
    :HOSTNAME => PREFIX + "-test",
    :IP => "192.168.0.201",
    :CPU => "6",
    :RAM => "2048"
  },
  {
    :HOSTNAME => PREFIX + "-prod",
    :IP => "192.168.0.202",
    :CPU => "6",
    :RAM => "2048"
  }
]

Vagrant.configure(2) do |config|

  SERVERS.each do |machine|

    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.define machine[:HOSTNAME] do |node|

        node.vm.box = "ubuntu/jammy64"
        node.vm.hostname = machine[:HOSTNAME]
        node.vm.network "public_network", bridge: "wlp3s0",
          ip: machine[:IP],
          netmask: NETMASK,
          gateway: GATEWAY

        node.vm.provider "virtualbox" do |vb|
            vb.memory = machine[:RAM]
            vb.cpus = machine[:CPU]
            vb.name = machine[:HOSTNAME]
        end # END of provider

        node.vm.provision "shell", inline: <<-SHELL
          sudo ip route del default via 10.0.2.2
          sudo sed -i "/#PubkeyAuthentication.*/a \PubkeyAcceptedKeyTypes=+ssh-rsa" /etc/ssh/sshd_config
          sudo systemctl restart sshd
          sudo apt-get update
          # Install Apache
          sudo apt-get install apache2 apache2-utils -y
          sudo systemctl enable apache2 && systemctl start apache2
        SHELL

    end # END of define

  end # END of SERVERS

end
